name: animore
markdown: redcarpet
pygments: true
email: maizi.wxx@alibaba-inc.com
description: "A websit which allow the designer to upload a creative, and someone to finish it."
permalink: /:year/:month/:title/
url: 
author:
    name: Nii Adjetey Sowah
    twitter: #